#include "g_local.h"

enum {
    kUnitInfo_unitID = 1,
    kUnitInfo_sort,
    kUnitInfo_comment,
    kUnitInfo_race,
    kUnitInfo_prio,
    kUnitInfo_threat,
    kUnitInfo_type,
    kUnitInfo_valid,
    kUnitInfo_deathType,
    kUnitInfo_death,
    kUnitInfo_canSleep,
    kUnitInfo_cargoSize,
    kUnitInfo_movetp,
    kUnitInfo_moveHeight,
    kUnitInfo_moveFloor,
    kUnitInfo_launchX,
    kUnitInfo_launchY,
    kUnitInfo_launchZ,
    kUnitInfo_impactZ,
    kUnitInfo_turnRate,
    kUnitInfo_propWin,
    kUnitInfo_orientInterp,
    kUnitInfo_formation,
    kUnitInfo_castpt,
    kUnitInfo_castbsw,
    kUnitInfo_targType,
    kUnitInfo_pathTex,
    kUnitInfo_fatLOS,
    kUnitInfo_collision,
    kUnitInfo_points,
    kUnitInfo_buffType,
    kUnitInfo_buffRadius,
    kUnitInfo_nameCount,
    kUnitInfo_InBeta,
};

struct SheetLayout unit_info[] = {
    { kUnitInfo_unitID, ST_ID, FOFS(UnitData, unitID) },
    { kUnitInfo_sort, ST_STRING, FOFS(UnitData, sort) },
    { kUnitInfo_comment, ST_STRING, FOFS(UnitData, comment) },
    { kUnitInfo_race, ST_STRING, FOFS(UnitData, race) },
    { kUnitInfo_prio, ST_INT, FOFS(UnitData, prio) },
    { kUnitInfo_threat, ST_INT, FOFS(UnitData, threat) },
    { kUnitInfo_type, ST_INT, FOFS(UnitData, type) },
    { kUnitInfo_valid, ST_INT, FOFS(UnitData, valid) },
    { kUnitInfo_deathType, ST_INT, FOFS(UnitData, deathType) },
    { kUnitInfo_death, ST_FLOAT, FOFS(UnitData, death) },
    { kUnitInfo_canSleep, ST_INT, FOFS(UnitData, canSleep) },
    { kUnitInfo_cargoSize, ST_INT, FOFS(UnitData, cargoSize) },
    { kUnitInfo_movetp, ST_STRING, FOFS(UnitData, movetp) },
    { kUnitInfo_moveHeight, ST_INT, FOFS(UnitData, moveHeight) },
    { kUnitInfo_moveFloor, ST_INT, FOFS(UnitData, moveFloor) },
    { kUnitInfo_launchX, ST_INT, FOFS(UnitData, launchX) },
    { kUnitInfo_launchY, ST_INT, FOFS(UnitData, launchY) },
    { kUnitInfo_launchZ, ST_INT, FOFS(UnitData, launchZ) },
    { kUnitInfo_impactZ, ST_INT, FOFS(UnitData, impactZ) },
    { kUnitInfo_turnRate, ST_FLOAT, FOFS(UnitData, turnRate) },
    { kUnitInfo_propWin, ST_INT, FOFS(UnitData, propWin) },
    { kUnitInfo_orientInterp, ST_INT, FOFS(UnitData, orientInterp) },
    { kUnitInfo_formation, ST_INT, FOFS(UnitData, formation) },
    { kUnitInfo_castpt, ST_FLOAT, FOFS(UnitData, castpt) },
    { kUnitInfo_castbsw, ST_FLOAT, FOFS(UnitData, castbsw) },
    { kUnitInfo_targType, ST_STRING, FOFS(UnitData, targType) },
    { kUnitInfo_pathTex, ST_STRING, FOFS(UnitData, pathTex) },
    { kUnitInfo_fatLOS, ST_INT, FOFS(UnitData, fatLOS) },
    { kUnitInfo_collision, ST_INT, FOFS(UnitData, collision) },
    { kUnitInfo_points, ST_INT, FOFS(UnitData, points) },
    { kUnitInfo_buffType, ST_INT, FOFS(UnitData, buffType) },
    { kUnitInfo_buffRadius, ST_INT, FOFS(UnitData, buffRadius) },
    { kUnitInfo_nameCount, ST_INT, FOFS(UnitData, nameCount) },
    { kUnitInfo_InBeta, ST_INT, FOFS(UnitData, InBeta) },
    { 0 }
};

void G_InitUnits(void) {
    game.UnitData = FS_ParseSheet("Units\\UnitData.slk", unit_info, sizeof(struct UnitData), FOFS(UnitData, lpNext));
}
