#ifndef s_skills_h
#define s_skills_h

#include "../g_local.h"

extern ability_t a_harvest;
extern ability_t a_move;
extern ability_t a_attack;
extern ability_t a_build;
extern ability_t a_train;
extern ability_t a_goldmine;
extern ability_t a_cancel;
extern ability_t a_repair;
extern ability_t a_stop;
extern ability_t a_holdpos;
extern ability_t a_patrol;
extern ability_t a_militia;
extern ability_t a_selectskill;
extern ability_t a_devotionaura;
extern ability_t a_holylight;
extern ability_t a_thunderbolt;
extern ability_t a_firebolt;
extern ability_t a_water_elemental;
extern ability_t a_feral_spirit;
extern ability_t a_blizzard;
extern ability_t a_carrion_swarm;
extern ability_t a_channel_test;
extern ability_t a_immolation;
extern ability_t a_phoenix_fire;
extern ability_t a_cold_arrows;
extern ability_t a_charm;
extern ability_t a_eat_tree;
extern ability_t a_moon_well;
extern ability_t a_invulnerable;
extern ability_t a_goldmine_overlayed;
extern ability_t a_blighted_goldmine;
extern ability_t a_blight;
extern ability_t a_acolyte_harvest;
extern ability_t a_return_resources;
extern ability_t a_wisp_harvest;
extern ability_t a_harvest_lumber;
extern ability_t a_repair_generic;
extern ability_t a_root;
extern ability_t a_entangle_goldmine;
extern ability_t a_entangled_mine;
extern ability_t a_cargo_hold;
extern ability_t a_cargo_hold_burrow;
extern ability_t a_cargo_hold_entangled_mine;
extern ability_t a_stand_down;
extern ability_t a_load;
extern ability_t a_drop;
extern ability_t a_drop_instant;
extern ability_t a_inventory;
extern ability_t a_shop_purchase_item;
extern ability_t a_neutral_building;
extern ability_t a_shop_sharing;
extern ability_t a_couple_instant;
extern ability_t a_item_heal;
extern ability_t a_item_mana_regain;
extern ability_t a_item_attack_bonus;
extern ability_t a_item_stat_bonus;
extern ability_t a_item_permanent_stat_gain;
extern ability_t a_item_defense_bonus;
extern ability_t a_item_life_bonus;
extern ability_t a_item_mana_bonus;
extern ability_t a_item_figurine_summon;
extern ability_t a_item_permanent_life_gain;
extern ability_t a_item_experience_gain;
extern ability_t a_item_level_gain;

FLOAT AB_Number(LPCSTR classname, LPCSTR field);
DWORD S_SpellCurrentCode(LPEDICT clent, DWORD fallback);
DWORD S_SpellLevel(LPEDICT caster, DWORD code);
FLOAT S_SpellNumber(DWORD code, LPCSTR field, DWORD level);
LPCSTR S_SpellString(DWORD code, LPCSTR field, DWORD level);
FLOAT S_SpellData(DWORD code, DWORD level, DWORD index);
DWORD S_SpellUnitId(DWORD code, DWORD level);
FLOAT S_SpellRange(DWORD code, DWORD level);
FLOAT S_SpellDuration(DWORD code, DWORD level, BOOL hero);
BOOL S_SpellCooldownReady(LPEDICT caster, DWORD code);
void S_SpellStartCooldown(LPEDICT caster, DWORD code, DWORD level);
BOOL S_SpellSpendMana(LPEDICT caster, DWORD code, DWORD level);
BOOL S_SpellCanPay(LPEDICT caster, DWORD code, DWORD level);
BOOL S_SpellTargetInRange(LPEDICT caster, LPEDICT target, FLOAT range);
BOOL S_SpellIsAliveTarget(LPEDICT target);
BOOL S_SpellIsEnemy(LPEDICT caster, LPEDICT target);
BOOL S_SpellIsFriend(LPEDICT caster, LPEDICT target);
BOOL S_SpellAllowsTarget(DWORD code, LPEDICT caster, LPEDICT target);
void S_SpellHeal(LPEDICT target, FLOAT amount);
void S_SpellSpawnTargetArt(LPEDICT target, LPCSTR art);
void S_SpellCursorSplat(LPEDICT clent, FLOAT radius);
void S_SpellCodeString(DWORD code, LPSTR out);

#endif
