#include "s_skills.h"

#ifdef WC3_DEBUG_AUTOCAST
int G_AutocastDebugLevel(void) {
    LPCSTR value;

    value = gi.CvarString("wc3_autocast_debug", "0");
    return value ? atoi(value) : 0;
}
#endif

typedef struct {
    LPCSTR classname;
    ability_t *ability;
} abilityitem_t;

/* ROC/TFT physical data columns are normalized by the AbilityData DDX schema. */
FLOAT AB_Data(LPCSTR classname, DWORD level, DWORD index) {
    AbilityData_t const *row = G_AbilityDataName(classname);
    level = MAX(1, MIN(level, 4)); index = MAX(1, MIN(index, 9));
    return row->data[level - 1][index - 1];
}

DWORD AB_DataId(LPCSTR classname, DWORD level, DWORD index) {
    AbilityData_t const *row = G_AbilityDataName(classname);
    level = MAX(1, MIN(level, 4)); index = MAX(1, MIN(index, 9));
    return row->dataId[level - 1][index - 1];
}

static abilityitem_t abilitylist[] = {
    { STR_CmdStop, &a_stop },
    { STR_CmdMove, &a_move },
    { STR_CmdAttack, &a_attack },
    { STR_CmdBuild, &a_build },
    { STR_CmdHoldPos, &a_holdpos },
    { STR_CmdPatrol, &a_patrol },
    { STR_CmdRally, &a_rally },
    { STR_CmdCancel, &a_cancel },
    { STR_CmdCancelBuild, &a_cancel },
    { STR_CmdSelectSkill, &a_selectskill },

    { "Ahar", &a_harvest },
    { "Amic", &a_call_to_arms },
    { "Amil", &a_militia },
    { "Arep", &a_repair },
    { "Agld", &a_goldmine },
    { "AHad", &a_devotionaura },
    { "AHhb", &a_holylight },
    { "AHwe", &a_water_elemental },
    { "AHbz", &a_blizzard },
    { "AHtb", &a_thunderbolt },
    { "ANfb", &a_firebolt },
    { "Apxf", &a_phoenix_fire },
    { "AOsf", &a_feral_spirit },
    { "AOmi", &a_mirror_image },
    { "Abun", &a_cargo_hold_burrow },
    { "Astd", &a_stand_down },
    { "AEim", &a_immolation },
    { "Aenc", &a_cargo_hold_entangled_mine },
    { "Aent", &a_entangle_goldmine },
    { "Aegm", &a_entangled_mine },
    { "Aeat", &a_eat_tree },
    { "Ambt", &a_moon_well },
    { "ANch", &a_charm },
    { "AIco", &a_charm },
    { "AHca", &a_cold_arrows },
    { "Agl2", &a_goldmine_overlayed },
    { "Abgm", &a_blighted_goldmine },
    { "Abli", &a_blight },
    { "Aaha", &a_acolyte_harvest },
    { "Artn", &a_return_resources },
    { "Awha", &a_wisp_harvest },
    { "Ahrl", &a_harvest_lumber },
    { "ANcl", &a_channel_test },
    { "AUcs", &a_carrion_swarm },
    { "AInv", &a_inventory },
    { "Aren", &a_repair_generic },
    { "Arst", &a_repair_generic },
    { "Avul", &a_invulnerable },
    { "Apit", &a_shop_purchase_item },
    { "Aneu", &a_neutral_building },
    { "Aall", &a_shop_sharing },
    { "Acoi", &a_couple_instant },
    { "AIhe", &a_item_heal },
    { "AIma", &a_item_mana_regain },
    { "AIat", &a_item_attack_bonus },
    { "AIab", &a_item_stat_bonus },
    { "AIim", &a_item_permanent_stat_gain },
    { "AIsm", &a_item_permanent_stat_gain },
    { "AIam", &a_item_permanent_stat_gain },
    { "AIxm", &a_item_permanent_stat_gain },
    { "AIde", &a_item_defense_bonus },
    { "AIml", &a_item_life_bonus },
    { "AImm", &a_item_mana_bonus },
    { "AIfs", &a_item_figurine_summon },
    { "AImi", &a_item_permanent_life_gain },
    { "AIem", &a_item_experience_gain },
    { "AIlm", &a_item_level_gain },
    { "AIda", &a_item_defense_aoe },
    { "AIct", &a_item_change_time },
    { "Acar", &a_cargo_hold },
    { "Aloa", &a_load },
    { "Adro", &a_drop },
    { "Adri", &a_drop_instant },
    { "Aroo", &a_root },

    /* Night Elf Warden (Maiev) hero abilities. */
    { "AEbl", &a_blink },
    { "AEfk", &a_fan_of_knives },
    { "AEsh", &a_shadow_strike },

    /* Additional hero spells. */
    { "ANfs", &a_flame_strike },  /* Flame Strike (Pit Lord) */
    { "ANdr", &a_siphon_mana },  /* Siphon Mana (Blood Mage) */


/* Missing WC3 abilities with Game.dll C++ class names */
/* Generated by ability_map from Game.dll RTTI + AbilityData.slk */

// TODO: { "AHbz", &a_blizzard },  // Blizzard — CAbilityBlizzard [HERO] human
// TODO: { "AHab", &a_aura_brilliance },  // Brilliance Aura — CAbilityAuraBrilliance [HERO] human
// TODO: { "AHmt", &a_mass_teleport },  // Mass Teleport — CAbilityMassTeleport [HERO] human
// TODO: { "AHwe", &a_water_elemental },  // Summon Water Elemental — CAbilityWaterElemental [HERO] human
// TODO: { "ANst", &a_stomp },  // Stampede — CAbilityStomp [HERO] creeps
// TODO: { "ANsg", &a_force_of_nature },  // Summon Bear — CAbilityForceOfNature [HERO] creeps
// TODO: { "ANsq", &a_force_of_nature },  // Summon Quilbeast — CAbilityForceOfNature [HERO] creeps
// TODO: { "ANsw", &a_force_of_nature },  // Summon Hawk — CAbilityForceOfNature [HERO] creeps
// TODO: { "AOww", &a_whirlwind },  // Bladestorm — CAbilityWhirlwind [HERO] orc
// TODO: { "AOcr", &a_critical_strike },  // Critical Strike — CAbilityCriticalStrike [HERO] orc
// TODO: { "AOmi", &a_mirror_image },  // Mirror Image — CAbilityMirrorImage [HERO] orc
// TODO: { "AOwk", &a_wind_walk },  // Wind Walk — CAbilityWindWalk [HERO] orc
// TODO: { "AHbn", &a_spell },  // Banish — CAbilitySpell [HERO] human
// TODO: { "AHfs", &a_rain_of_fire },  // Flame Strike — CAbilityRainOfFire [HERO] human
// TODO: { "AHdr", &a_spell },  // Siphon Mana — CAbilitySpell [HERO] human
// TODO: { "AHpx", &a_morph },  // Phoenix — CAbilityMorph [HERO] human
// TODO: { "AUcb", &a_morph },  // Carrion Beetles — CAbilityMorph [HERO] undead
// TODO: { "AUim", &a_stomp },  // Impale — CAbilityStomp [HERO] undead
// TODO: { "AUls", &a_creep_sleep },  // Locust Swarm — CAbilityCreepSleep [HERO] undead
// TODO: { "AUts", &a_aura },  // Spiked Carapace — CAbilityAura [HERO] undead
// TODO: { "ANba", &a_poison_attack },  // Black Arrow — CAbilityPoisonAttack [HERO] creeps
// TODO: { "ANch", &a_spell },  // Charm — CAbilitySpell [HERO] creeps
// TODO: { "ANsi", &a_spell },  // Silence — CAbilitySpell [HERO] creeps
// TODO: { "AUan", &a_revenge },  // Animate Dead — CAbilityRevenge [HERO] undead
// TODO: { "AUdc", &a_spell },  // Death Coil — CAbilitySpell [HERO] undead
// TODO: { "AUdp", &a_spell },  // Death Pact — CAbilitySpell [HERO] undead
// TODO: { "AUau", &a_aura_regen_life },  // Unholy Aura — CAbilityAuraRegenLife [HERO] undead
// TODO: { "AEev", &a_evasion },  // Evasion — CAbilityEvasion [HERO] nightelf
// TODO: { "AEim", &a_immolation },  // Immolation — CAbilityImmolation [HERO] nightelf
// TODO: { "AEmb", &a_spell },  // Mana Burn — CAbilitySpell [HERO] nightelf
// TODO: { "AEme", &a_morph },  // Metamorphosis — CAbilityMorph [HERO] nightelf
// TODO: { "AUsl", &a_creep_sleep },  // Sleep — CAbilityCreepSleep [HERO] undead
// TODO: { "AUav", &a_aura },  // Vampiric Aura — CAbilityAura [HERO] undead
// TODO: { "AUcs", &a_carrion_swarm },  // Carrion Swarm — CAbilityCarrionSwarm [HERO] undead
// TODO: { "AUin", &a_stomp },  // Inferno — CAbilityStomp [HERO] undead
// TODO: { "AOcl", &a_chain_lightning },  // Chain Lightning — CAbilityChainLightning [HERO] orc
// TODO: { "AOeq", &a_earthquake },  // Earthquake — CAbilityEarthquake [HERO] orc
// TODO: { "AOfs", &a_far_sight },  // Far Sight — CAbilityFarSight [HERO] orc
// TODO: { "AOsf", &a_spirit_wolf },  // Feral Spirit — CAbilitySpiritWolf [HERO] orc
// TODO: { "AEer", &a_target },  // Entangling Roots — CAbilityTarget [HERO] nightelf
// TODO: { "AEfn", &a_force_of_nature },  // Force of Nature — CAbilityForceOfNature [HERO] nightelf
// TODO: { "AEah", &a_aura_spell },  // Thorns Aura — CAbilityAuraSpell [HERO] nightelf
// TODO: { "AEtq", &a_aura_regen_life },  // Tranquility — CAbilityAuraRegenLife [HERO] nightelf
// TODO: { "AUdr", &a_spell },  // Dark Ritual — CAbilitySpell [HERO] undead
// TODO: { "AUdd", &a_rain_of_fire },  // Death And Decay — CAbilityRainOfFire [HERO] undead
// TODO: { "AUfa", &a_spell },  // Frost Armor — CAbilitySpell [HERO] undead
// TODO: { "AUfu", &a_spell },  // Frost Armor — CAbilitySpell [HERO] undead
// TODO: { "AUfn", &a_frost_nova },  // Frost Nova — CAbilityFrostNova [HERO] undead
// TODO: { "AHav", &a_attribute_mod },  // Avatar — CAbilityAttributeMod [HERO] human
// TODO: { "AHbh", &a_bash },  // Bash — CAbilityBash [HERO] human
// TODO: { "AHtb", &a_thunder_bolt },  // Storm Bolt — CAbilityThunderBolt [HERO] human
// TODO: { "AHtc", &a_thunder_clap },  // Thunder Clap — CAbilityThunderClap [HERO] human
// TODO: { "ANfl", &a_bounce },  // Forked Lightning — CAbilityBounce [HERO] creeps
// TODO: { "ANfa", &a_poison_attack },  // Frost Arrows — CAbilityPoisonAttack [HERO] creeps
// TODO: { "ANto", &a_whirlwind },  // Tornado — CAbilityWhirlwind [HERO] creeps
// TODO: { "ANms", &a_aura },  // Mana Shield — CAbilityAura [HERO] creeps
// TODO: { "AHad", &a_aura_brilliance },  // Devotion Aura — CAbilityAuraBrilliance [HERO] human
// TODO: { "AHds", &a_invulnerable },  // Divine Shield — CAbilityInvulnerable [HERO] human
// TODO: { "AHhb", &a_holy_light },  // Holy Light — CAbilityHolyLight [HERO] human
// TODO: { "AHre", &a_revive },  // Resurrection — CAbilityRevive [HERO] human
// TODO: { "ANbf", &a_immolation },  // Breath of Fire — CAbilityImmolation [HERO] creeps
// TODO: { "ANdb", &a_revenge },  // Drunken Brawler — CAbilityRevenge [HERO] creeps
// TODO: { "ANdh", &a_spell },  // Drunken Haze — CAbilitySpell [HERO] creeps
// TODO: { "ANef", &a_button },  // "Storm, Earth, And Fire" — CAbilityButton [HERO] creeps
// TODO: { "ANdo", &a_spell },  // Doom — CAbilitySpell [HERO] creeps
// TODO: { "ANht", &a_healing_ward },  // Howl of Terror — CAbilityHealingWard [HERO] creeps
// TODO: { "ANca", &a_chain_lightning },  // Cleaving Attack — CAbilityChainLightning [HERO] creeps
// TODO: { "ANrf", &a_rain_of_fire },  // Rain of Fire — CAbilityRainOfFire [HERO] creeps
// TODO: { "AHfa", &a_poison_attack },  // Searing Arrows — CAbilityPoisonAttack [HERO] nightelf
// TODO: { "AEst", &a_button },  // Scout — CAbilityButton [HERO] nightelf
// TODO: { "AEsf", &a_whirlwind },  // Starfall — CAbilityWhirlwind [HERO] nightelf
// TODO: { "AEar", &a_aura },  // Trueshot Aura — CAbilityAura [HERO] nightelf
// TODO: { "AOae", &a_aura_endurance },  // Endurance Aura — CAbilityAuraEndurance [HERO] orc
// TODO: { "AOre", &a_reincarnation },  // Reincarnation — CAbilityReincarnation [HERO] orc
// TODO: { "AOsh", &a_shockwave },  // Shockwave — CAbilityShockwave [HERO] orc
// TODO: { "AOws", &a_war_stomp },  // War Stomp — CAbilityWarStomp [HERO] orc
// TODO: { "AOhw", &a_spell },  // Healing Wave — CAbilitySpell [HERO] orc
// TODO: { "AOhx", &a_spell },  // Hex — CAbilitySpell [HERO] orc
// TODO: { "AOsw", &a_morph },  // Serpent Ward — CAbilityMorph [HERO] orc
// TODO: { "AOvd", &a_spell },  // Big Bad Voodoo — CAbilitySpell [HERO] orc
// TODO: { "AEbl", &a_move },  // Blink — CAbilityMove [HERO] nightelf
// TODO: { "AEfk", &a_bounce },  // Fan of Knives — CAbilityBounce [HERO] nightelf
// TODO: { "AEsh", &a_thunder_bolt },  // Shadow Strike — CAbilityThunderBolt [HERO] nightelf
// TODO: { "AEsv", &a_morph },  // Vengeance — CAbilityMorph [HERO] nightelf
// TODO: { "ANab", &a_button },  // Acid Bomb — CAbilityButton [HERO] creeps
// TODO: { "ANcr", &a_critical_strike },  // Chemical Rage — CAbilityCriticalStrike [HERO] creeps
// TODO: { "ANhs", &a_heal },  // Healing Spray — CAbilityHeal [HERO] creeps
// TODO: { "ANtm", &a_aura_regen_life },  // Transmute — CAbilityAuraRegenLife [HERO] creeps
// TODO: { "ANeg", &a_evasion },  // Engineering Upgrade — CAbilityEvasion [HERO] creeps
// TODO: { "ANcs", &a_spell },  // Cluster Rockets — CAbilitySpell [HERO] creeps
// TODO: { "ANrg", &a_regen_base },  // Robo-Goblin — CAbilityRegenBase [HERO] creeps
// TODO: { "ANsy", &a_button },  // Pocket Factory — CAbilityButton [HERO] creeps
// TODO: { "ANde", &a_button },  // Demolish — CAbilityButton [HERO] creeps
// TODO: { "ANic", &a_inner_fire },  // Incinerate — CAbilityInnerFire [HERO] creeps
// TODO: { "ANia", &a_inner_fire },  // Incinerate — CAbilityInnerFire [HERO] creeps
// TODO: { "ANso", &a_spell },  // Soul Burn — CAbilitySpell [HERO] creeps
// TODO: { "ANlm", &a_lightning_shield },  // Summon Lava Spawn — CAbilityLightningShield [HERO] creeps
// TODO: { "ANvc", &a_spell },  // Volcano — CAbilitySpell [HERO] creeps
// TODO: { "ANin", &a_creep_thunder_bolt },  // Inferno — CAbilityCreepThunderBolt [HERO] creeps
// TODO: { "ANfb", &a_creep_thunder_bolt },  // Firebolt — CAbilityCreepThunderBolt [HERO] creeps
// TODO: { "ANfd", &a_spell },  // Finger of Death — CAbilitySpell [HERO] creeps
// TODO: { "ANdp", &a_mass_teleport },  // Dark Portal — CAbilityMassTeleport [HERO] creeps
// TODO: { "ANrc", &a_rain_of_fire },  // Rain of Chaos — CAbilityRainOfFire [HERO] creeps
// TODO: { "ANdc", &a_spell },  // Dark Conversion — CAbilitySpell [HERO] creeps
// TODO: { "ANsl", &a_spell },  // Soul Preservation — CAbilitySpell [HERO] creeps
// TODO: { "ANmo", &a_bounce },  // Monsoon — CAbilityBounce [HERO] creeps
// TODO: { "AEpa", &a_poison_attack },  // Poison Arrows — CAbilityPoisonAttack [HERO] creeps
// TODO: { "ANwm", &a_war_stomp },  // Watery Minion — CAbilityWarStomp [HERO] creeps
// TODO: { "AHca", &a_poison_attack },  // Cold Arrows — CAbilityPoisonAttack [HERO] creeps
// TODO: { "ANbr", &a_bash },  // Battle Roar — CAbilityBash [HERO] creeps
// TODO: { "Aamk", &a_attack_mod },  // Attribute Modifier Skill — CAbilityAttackMod [HERO] creeps
// TODO: { "Arsw", &a_revive },  // Rokhan - Serpent Ward — CAbilityRevive [HERO] orc
// TODO: { "ANcl", &a_spell },  // Illidan - Channel — CAbilitySpell [HERO] creeps
// TODO: { "Aadm", &a_auto_dispel_magic },  // Abolish Magic — CAbilityAutoDispelMagic nightelf
// TODO: { "Aabs", &a_aura },  // Absorb Mana — CAbilityAura undead
// TODO: { "Aaha", &a_harvest },  // Gather — CAbilityHarvest undead
// TODO: { "Aalr", &a_alarm },  // Alarm — CAbilityAlarm other
// TODO: { "Aall", &a_button },  // Shop Sharing, Allied Bldg. — CAbilityButton other
// TODO: { "Aast", &a_aura },  // Ancestral Spirit — CAbilityAura orc
// TODO: { "ACad", &a_revenge },  // Animate Dead — CAbilityRevenge creeps
// TODO: { "Aams", &a_magic_immunity },  // Anti-magic Shell — CAbilityMagicImmunity undead
// TODO: { "Aatk", &a_attack },  // Attack — CAbilityAttack other
// TODO: { "ACac", &a_aura_command },  // Command Aura — CAbilityAuraCommand creeps
// TODO: { "Aap1", &a_on_fire },  // Disease Cloud — CAbilityOnFire undead
// TODO: { "Aap2", &a_poison_attack },  // Disease Cloud — CAbilityPoisonAttack undead
// TODO: { "Aap3", &a_poison_attack },  // Disease Cloud — CAbilityPoisonAttack creeps
// TODO: { "Aap4", &a_poison_attack },  // Disease Cloud — CAbilityPoisonAttack creeps
// TODO: { "Aoar", &a_aura_regen_life },  // Healing Ward Aura — CAbilityAuraRegenLife orc
// TODO: { "Aabr", &a_aura_regen_life },  // Aura of Blight — CAbilityAuraRegenLife undead
// TODO: { "Aasl", &a_slow },  // Slow Aura — CAbilitySlow naga
// TODO: { "Aakb", &a_aura_command },  // War Drums — CAbilityAuraCommand orc
// TODO: { "Aave", &a_stomp },  // Destroyer Form  — CAbilityStomp undead
// TODO: { "Aawa", &a_war_stomp },  // Revive Hero Instantly — CAbilityWarStomp other
// TODO: { "Abof", &a_aura_command },  // Burning Oil — CAbilityAuraCommand orc
// TODO: { "Abtl", &a_battlestations },  // Battle Stations — CAbilityBattlestations orc
// TODO: { "Abrf", &a_morph },  // Bear Form — CAbilityMorph nightelf
// TODO: { "Absk", &a_button },  // Berserk — CAbilityButton orc
// TODO: { "Sbsk", &a_button },  // Berserker Upgrade — CAbilityButton orc
// TODO: { "Abds", &a_morph },  // Blight Dispel Small — CAbilityMorph other
// TODO: { "Abdl", &a_creep_sleep },  // Blight Dispel Large — CAbilityCreepSleep other
// TODO: { "Abgs", &a_ghost },  // Blight Growth Small — CAbilityGhost undead
// TODO: { "Abgl", &a_ghost },  // Blight Growth Large — CAbilityGhost undead
// TODO: { "Abgm", &a_gold_mine_base },  // Blighted Gold Mine Ability — CAbilityGoldMineBase undead
// TODO: { "Ablo", &a_bloodlust },  // Bloodlust — CAbilityBloodlust orc
// TODO: { "ACbf", &a_on_fire },  // Breath of Frost — CAbilityOnFire creeps
// TODO: { "ANbu", &a_neutral_build },  // Build (Neutral) — CAbilityNeutralBuild other
// TODO: { "AHbu", &a_human_build },  // Build (Human) — CAbilityHumanBuild human
// TODO: { "AObu", &a_orc_build },  // Build (Orc) — CAbilityOrcBuild orc
// TODO: { "AEbu", &a_night_elf_build },  // Build (Night Elf) — CAbilityNightElfBuild nightelf
// TODO: { "AUbu", &a_undead_build },  // Build (Undead) — CAbilityUndeadBuild undead
// TODO: { "AGbu", &a_neutral_build },  // Build (Naga) — CAbilityNeutralBuild other
// TODO: { "Abur", &a_creep_sleep },  // Burrow — CAbilityCreepSleep undead
// TODO: { "Abdt", &a_creep_sleep },  // Burrow Detection — CAbilityCreepSleep other
// TODO: { "Acan", &a_cannibalize },  // Cannibalize — CAbilityCannibalize undead
// TODO: { "Abun", &a_bunker },  // Cargo Hold (Orc Burrow) — CAbilityBunker orc
// TODO: { "Advc", &a_devour_cargo },  // Devour Cargo — CAbilityDevourCargo orc
// TODO: { "Sch2", &a_cargo_hold },  // Cargo Hold — CAbilityCargoHold undead
// TODO: { "Sch5", &a_cargo_hold },  // Cargo Hold — CAbilityCargoHold other
// TODO: { "Sch4", &a_cargo_hold },  // Cargo Hold — CAbilityCargoHold human
// TODO: { "Sch3", &a_cargo_hold },  // Cargo Hold — CAbilityCargoHold other
// TODO: { "Aenc", &a_cargo_hold },  // Load — CAbilityCargoHold nightelf
// TODO: { "Achd", &a_cargo_hold },  // Cargo Hold Death — CAbilityCargoHold other
// TODO: { "Ache", &a_cargo_hold },  // Ray of Disruption — CAbilityCargoHold creeps
// TODO: { "Sca1", &a_bounce },  // Chaos (Grunt) — CAbilityBounce orc
// TODO: { "Sca2", &a_cargo_hold },  // Chaos (Raider) — CAbilityCargoHold orc
// TODO: { "Sca3", &a_cargo_hold },  // Chaos (Shaman) — CAbilityCargoHold orc
// TODO: { "Sca4", &a_cargo_hold },  // Chaos (Kodo) — CAbilityCargoHold orc
// TODO: { "Sca5", &a_cargo_hold },  // Chaos (Peon) — CAbilityCargoHold orc
// TODO: { "Sca6", &a_cargo_hold },  // Chaos (Grom) — CAbilityCargoHold orc
// TODO: { "Achl", &a_cargo_load },  // Chaos Cargo Load — CAbilityCargoLoad orc
// TODO: { "Aclf", &a_bounce },  // Cloud — CAbilityBounce human
// TODO: { "Acmg", &a_spell },  // Control Magic — CAbilitySpell human
// TODO: { "Acpf", &a_purge },  // Corporeal Form — CAbilityPurge orc
// TODO: { "Acor", &a_bounce },  // Corrosive Breath — CAbilityBounce nightelf
// TODO: { "Acoa", &a_morph },  // Mount Hippogryph — CAbilityMorph nightelf
// TODO: { "Acoh", &a_morph },  // Pick up Archer — CAbilityMorph nightelf
// TODO: { "Aco2", &a_cargo_load },  // Mount Hippogryph — CAbilityCargoLoad nightelf
// TODO: { "Aco3", &a_cargo_load },  // Pick up Archer — CAbilityCargoLoad nightelf
// TODO: { "ACsp", &a_creep_sleep },  // Sleep — CAbilityCreepSleep creeps
// TODO: { "Acri", &a_cripple },  // Cripple — CAbilityCripple undead
// TODO: { "Acrs", &a_auto_target_spell },  // Curse — CAbilityAutoTargetSpell undead
// TODO: { "Acyc", &a_morph },  // Cyclone — CAbilityMorph nightelf
// TODO: { "Adda", &a_on_fire },  // AOE damage upon death — CAbilityOnFire other
// TODO: { "Adec", &a_defend },  // Dismount — CAbilityDefend nightelf
// TODO: { "Adef", &a_defend },  // Defend — CAbilityDefend human
// TODO: { "Adt1", &a_detector },  // Detector — CAbilityDetector orc
// TODO: { "Atru", &a_true_sight },  // True Sight — CAbilityTrueSight undead
// TODO: { "Agyv", &a_true_sight },  // True Sight — CAbilityTrueSight human
// TODO: { "Adts", &a_magic_sentry },  // Magic Sentry — CAbilityMagicSentry human
// TODO: { "Adtn", &a_button },  // Detonate — CAbilityButton nightelf
// TODO: { "Adev", &a_devour },  // Devour — CAbilityDevour orc
// TODO: { "ACdv", &a_creep_devour },  // Devour — CAbilityCreepDevour creeps
// TODO: { "Advm", &a_dispel_magic },  // Devour Magic — CAbilityDispelMagic undead
// TODO: { "Adch", &a_spell },  // Disenchant — CAbilitySpell orc
// TODO: { "Adcn", &a_spell },  // Disenchant — CAbilitySpell orc
// TODO: { "Adis", &a_dispel_magic },  // Dispel Magic — CAbilityDispelMagic human
// TODO: { "Adri", &a_cargo_drop_instant },  // Unload Instant — CAbilityCargoDropInstant other
// TODO: { "Adro", &a_cargo_drop },  // Unload — CAbilityCargoDrop other
// TODO: { "Atdp", &a_cargo_drop },  // Drop Pilot — CAbilityCargoDrop human
// TODO: { "Aeat", &a_harvest },  // Eat Tree — CAbilityHarvest nightelf
// TODO: { "Aegr", &a_target },  // Elune's Grace — CAbilityTarget nightelf
// TODO: { "ANen", &a_ensnare },  // Ensnare(Naga) — CAbilityEnsnare naga
// TODO: { "Aens", &a_ensnare },  // Ensnare — CAbilityEnsnare orc
// TODO: { "Aent", &a_gold_mine },  // Entangle Gold Mine — CAbilityGoldMine nightelf
// TODO: { "Aegm", &a_gold_mine },  // Entangled Gold Mine Ability — CAbilityGoldMine nightelf
// TODO: { "Aetl", &a_button },  // Ethereal — CAbilityButton nightelf
// TODO: { "Aetf", &a_morph },  // Ethereal Form — CAbilityMorph orc
// TODO: { "Aexh", &a_button },  // Exhume Corpses — CAbilityButton undead
// TODO: { "ANfy", &a_on_fire },  // Factory — CAbilityOnFire creeps
// TODO: { "Afae", &a_auto_target_spell },  // Faerie Fire — CAbilityAutoTargetSpell nightelf
// TODO: { "Afbk", &a_aura },  // Feedback — CAbilityAura human
// TODO: { "Aflk", &a_button },  // Flak Cannons — CAbilityButton human
// TODO: { "Afla", &a_button },  // Flare — CAbilityButton human
// TODO: { "Afsh", &a_button },  // Fragmentation Shards — CAbilityButton human
// TODO: { "Afrz", &a_frost_nova },  // Freezing Breath — CAbilityFrostNova undead
// TODO: { "Afzy", &a_spell },  // Frenzy — CAbilitySpell creeps
// TODO: { "Afra", &a_button },  // Frost Attack — CAbilityButton undead
// TODO: { "Afrb", &a_button },  // Frost Breath — CAbilityButton undead
// TODO: { "Agho", &a_ghost },  // Ghost — CAbilityGhost undead
// TODO: { "Aeth", &a_ghost },  // Ghost — CAbilityGhost undead
// TODO: { "Agld", &a_gold_mine },  // Gold Mine ability — CAbilityGoldMine other
// TODO: { "Agra", &a_poison_attack },  // War Club — CAbilityPoisonAttack nightelf
// TODO: { "Agyd", &a_simple_spell },  // Create Corpse — CAbilitySimpleSpell undead
// TODO: { "Agyb", &a_bounce },  // Flying Machine Bombs — CAbilityBounce human
// TODO: { "Assk", &a_button },  // Hardened Skin — CAbilityButton nightelf
// TODO: { "Ahar", &a_harvest },  // Harvest — CAbilityHarvest other
// TODO: { "Ahrl", &a_harvest_lumber },  // Harvest — CAbilityHarvestLumber undead
// TODO: { "Ahea", &a_heal },  // Heal — CAbilityHeal human
// TODO: { "Anhe", &a_heal },  // Heal — CAbilityHeal creeps
// TODO: { "Ahwd", &a_healing_ward },  // Healing Ward — CAbilityHealingWard orc
// TODO: { "Ahnl", &a_heal },  // null roar (summoner) — CAbilityHeal naga
// TODO: { "AHer", &a_hero },  // Hero — CAbilityHero other
// TODO: { "Aimp", &a_bounce },  // Impaling Bolt — CAbilityBounce nightelf
// TODO: { "Ainf", &a_inner_fire },  // Inner Fire — CAbilityInnerFire human
// TODO: { "Aivs", &a_perm_invis },  // Invisibility — CAbilityPermInvis human
// TODO: { "AInv", &a_inventory },  // Inventory — CAbilityInventory other
// TODO: { "Avul", &a_invulnerable },  // Invulnerable — CAbilityInvulnerable other
// TODO: { "Alit", &a_lightning_attack },  // Lightning Attack — CAbilityLightningAttack nightelf
// TODO: { "Alsh", &a_lightning_shield },  // Lightning Shield — CAbilityLightningShield orc
// TODO: { "Aliq", &a_on_fire },  // Liquid Fire — CAbilityOnFire orc
// TODO: { "Aloa", &a_cargo_load },  // Load — CAbilityCargoLoad other
// TODO: { "Atlp", &a_cargo_load },  // Load Pilot — CAbilityCargoLoad human
// TODO: { "Aloc", &a_button },  // Locust — CAbilityButton undead
// TODO: { "Amdf", &a_aura },  // Magic Defense — CAbilityAura human
// TODO: { "Amim", &a_magic_immunity },  // Spell Immunity — CAbilityMagicImmunity nightelf
// TODO: { "Amls", &a_aura },  // Aerial Shackles — CAbilityAura human
// TODO: { "Ambt", &a_regen_mana },  // Replenish Mana and Life — CAbilityRegenMana nightelf
// TODO: { "Amfl", &a_frost_nova },  // Mana Flare — CAbilityFrostNova nightelf
// TODO: { "Amed", &a_cargo_drop },  // Drop Corpse — CAbilityCargoDrop undead
// TODO: { "Amel", &a_cargo_load },  // Get Corpse — CAbilityCargoLoad undead
// TODO: { "Amil", &a_morph },  // Call to Arms — CAbilityMorph human
// TODO: { "Amic", &a_base_build },  // Call To Arms — CAbilityBaseBuild human
// TODO: { "ANmr", &a_aura },  // Mind Rot — CAbilityAura creeps
// TODO: { "Amin", &a_button },  // Mine - exploding — CAbilityButton other
// TODO: { "Amgl", &a_bounce },  // Moon Glaive — CAbilityBounce nightelf
// TODO: { "Amov", &a_move },  // Move — CAbilityMove other
// TODO: { "Aneu", &a_neutral_build },  // Select Hero — CAbilityNeutralBuild other
// TODO: { "Andt", &a_evil_eye },  // Reveal — CAbilityEvilEye creeps
// TODO: { "ANre", &a_neutral_regen_mana },  // Mana Regeneration — CAbilityNeutralRegenMana creeps
// TODO: { "AAns", &a_neutral_spell },  // Charge Gold and Lumber — CAbilityNeutralSpell creeps
// TODO: { "Ansp", &a_neutral_spell },  // Neutral Spies — CAbilityNeutralSpell creeps
// TODO: { "Afak", &a_spell },  // Orb of Annihilation — CAbilitySpell undead
// TODO: { "Afir", &a_on_fire },  // On Fire — CAbilityOnFire other
// TODO: { "Afih", &a_on_fire_human },  // On Fire (Human) — CAbilityOnFireHuman human
// TODO: { "Afio", &a_on_fire_orc },  // On Fire (Orc) — CAbilityOnFireOrc orc
// TODO: { "Afin", &a_on_fire_night_elf },  // On Fire (Night Elf) — CAbilityOnFireNightElf nightelf
// TODO: { "Afiu", &a_on_fire_undead },  // On Fire (Undead) — CAbilityOnFireUndead undead
// TODO: { "ANpa", &a_poison_attack },  // Parasite — CAbilityPoisonAttack naga
// TODO: { "ANpi", &a_perm_immolation },  // Permanent Immolation — CAbilityPermImmolation other
// TODO: { "Apig", &a_harvest_return },  // Permanent Immolation — CAbilityHarvestReturn other
// TODO: { "Apiv", &a_perm_invis },  // Permanent Invisibility — CAbilityPermInvis other
// TODO: { "Apsh", &a_stomp },  // Phase Shift — CAbilityStomp nightelf
// TODO: { "Aphx", &a_morph },  // Phoenix Morphing (Egg Related) — CAbilityMorph human
// TODO: { "Apxf", &a_perm_immolation },  // Phoenix Fire — CAbilityPermImmolation human
// TODO: { "Apts", &a_button },  // Disease Cloud — CAbilityButton undead
// TODO: { "Apoi", &a_poison_attack },  // Poison Sting — CAbilityPoisonAttack other
// TODO: { "Aply", &a_simple_spell },  // Polymorph — CAbilitySimpleSpell human
// TODO: { "Apos", &a_creep_sleep },  // Possession — CAbilityCreepSleep undead
// TODO: { "Aps2", &a_creep_sleep },  // Possession — CAbilityCreepSleep undead
// TODO: { "Awar", &a_bounce },  // Pulverize — CAbilityBounce orc
// TODO: { "Apit", &a_base_sell },  // Shop Purchase Item — CAbilityBaseSell other
// TODO: { "Aprg", &a_lightning_purge },  // Purge — CAbilityLightningPurge orc
// TODO: { "Arai", &a_simple_spell },  // Raise Dead — CAbilitySimpleSpell undead
// TODO: { "ARal", &a_rally },  // Rally — CAbilityRally other
// TODO: { "Arav", &a_raven_form },  // Storm Crow Form — CAbilityRavenForm nightelf
// TODO: { "ACrn", &a_creep_reincarnation },  // Reincarnation — CAbilityCreepReincarnation creeps
// TODO: { "Arbr", &a_button },  // Reinforced Burrows Upgrade — CAbilityButton orc
// TODO: { "Arej", &a_regen_life },  // Rejuvenation — CAbilityRegenLife nightelf
// TODO: { "Aren", &a_repair },  // Renew — CAbilityRepair nightelf
// TODO: { "Ahrp", &a_repair },  // Repair — CAbilityRepair human
// TODO: { "Arep", &a_repair },  // Repair — CAbilityRepair orc
// TODO: { "Arpb", &a_spell },  // Replenish — CAbilitySpell undead
// TODO: { "Arpl", &a_spell },  // Essence of Blight — CAbilitySpell undead
// TODO: { "Arpm", &a_spell },  // Spirit Touch — CAbilitySpell undead
// TODO: { "Arsk", &a_morph },  // Resistant Skin — CAbilityMorph nightelf
// TODO: { "Arst", &a_repair },  // Restore — CAbilityRepair undead
// TODO: { "Argd", &a_move },  // Return Gold — CAbilityMove other
// TODO: { "Argl", &a_harvest_return },  // Return Gold and Lumber — CAbilityHarvestReturn other
// TODO: { "Arlm", &a_reincarnation },  // Return Lumber — CAbilityReincarnation other
// TODO: { "AHta", &a_spell },  // Reveal — CAbilitySpell human
// TODO: { "Arng", &a_revenge },  // Revenge — CAbilityRevenge other
// TODO: { "Arev", &a_revive },  // Revive Hero — CAbilityRevive other
// TODO: { "Aroa", &a_roar },  // Roar — CAbilityRoar nightelf
// TODO: { "Aroc", &a_rain_of_fire },  // Barrage — CAbilityRainOfFire human
// TODO: { "Aro1", &a_roar },  // Root — CAbilityRoar nightelf
// TODO: { "Aro2", &a_roar },  // Root — CAbilityRoar nightelf
// TODO: { "Asac", &a_spell },  // Sacrifice — CAbilitySpell undead
// TODO: { "Asal", &a_button },  // Pillage — CAbilityButton orc
// TODO: { "Alam", &a_spell },  // Sacrifice — CAbilitySpell undead
// TODO: { "Asds", &a_button },  // Kaboom! — CAbilityButton creeps
// TODO: { "Asid", &a_button },  // Sell Items — CAbilityButton other
// TODO: { "Asud", &a_spell },  // Sell Units — CAbilitySpell other
// TODO: { "Aesn", &a_button },  // Sentinel — CAbilityButton nightelf
// TODO: { "Aeye", &a_button },  // Sentry Ward — CAbilityButton orc
// TODO: { "ACtn", &a_creep_thunder_clap },  // Serpent Ward (tentacle, Forgotten one) — CAbilityCreepThunderClap creeps
// TODO: { "Ashm", &a_shadow_meld },  // Shadow Meld — CAbilityShadowMeld nightelf
// TODO: { "Ahid", &a_shadow_meld },  // Shadow Meld — CAbilityShadowMeld creeps
// TODO: { "Asla", &a_sleep_always },  // Sleep Always — CAbilitySleepAlways creeps
// TODO: { "Aslo", &a_slow },  // Slow — CAbilitySlow human
// TODO: { "Aspo", &a_poison_attack },  // Slow Poison — CAbilityPoisonAttack nightelf
// TODO: { "Asod", &a_simple_spell },  // Spawn Skeleton — CAbilitySimpleSpell creeps
// TODO: { "Assp", &a_simple_spell },  // Spawn Spiderlings — CAbilitySimpleSpell creeps
// TODO: { "Aspd", &a_simple_spell },  // Spawn Spiders — CAbilitySimpleSpell creeps
// TODO: { "Asps", &a_creep_sleep },  // Spell Steal — CAbilityCreepSleep human
// TODO: { "Asph", &a_poison_attack },  // Sphere — CAbilityPoisonAttack human
// TODO: { "Aspa", &a_attack },  // Spider Attack — CAbilityAttack undead
// TODO: { "Aspi", &a_spiked },  // Spiked Barricades — CAbilitySpiked orc
// TODO: { "Aspl", &a_creep_sleep },  // Spirit Link — CAbilityCreepSleep orc
// TODO: { "Astd", &a_stand_down },  // Stand Down — CAbilityStandDown orc
// TODO: { "Asta", &a_stasis_trap },  // Stasis Trap — CAbilityStasisTrap orc
// TODO: { "Astn", &a_morph },  // Stone Form — CAbilityMorph undead
// TODO: { "Asth", &a_bounce },  // Storm Hammers — CAbilityBounce human
// TODO: { "Asb1", &a_slow },  // Submerge (Myrmidon) — CAbilitySlow creeps
// TODO: { "Asb2", &a_slow },  // Submerge (Royal Guard) — CAbilitySlow creeps
// TODO: { "Asb3", &a_slow },  // Submerge (Snap Dragon) — CAbilitySlow creeps
// TODO: { "Attu", &a_button },  // Turret — CAbilityButton human
// TODO: { "Srtt", &a_morph },  // Tank Upgrade — CAbilityMorph human
// TODO: { "Atau", &a_spell },  // Taunt — CAbilitySpell nightelf
// TODO: { "ACtb", &a_creep_thunder_bolt },  // Hurl Boulder — CAbilityCreepThunderBolt creeps
// TODO: { "ACtc", &a_creep_thunder_clap },  // Slam — CAbilityCreepThunderClap creeps
// TODO: { "Atdg", &a_stomp },  // Building Damage Aura — CAbilityStomp naga
// TODO: { "Atsp", &a_aura },  // Tornado Spin — CAbilityAura naga
// TODO: { "Atwa", &a_war_stomp },  // Tornado Wander — CAbilityWarStomp naga
// TODO: { "Atol", &a_upgrade },  // Tree of Life upgrade ability — CAbilityUpgrade nightelf
// TODO: { "Ault", &a_night_vision },  // Ultravision — CAbilityNightVision nightelf
// TODO: { "Auhf", &a_creep_sleep },  // Unholy Frenzy — CAbilityCreepSleep undead
// TODO: { "Auco", &a_spell },  // Unstable Concoction — CAbilitySpell orc
// TODO: { "Auns", &a_button },  // Unsummon Building — CAbilityButton undead
// TODO: { "SCva", &a_aura_regen_life },  // Life Steal — CAbilityAuraRegenLife creeps
// TODO: { "Avng", &a_revenge },  // Spirit of Vengeance — CAbilityRevenge nightelf
// TODO: { "Awan", &a_wander },  // Wander — CAbilityWander other
// TODO: { "Awha", &a_harvest },  // Gather — CAbilityHarvest nightelf
// TODO: { "Aven", &a_venom_spear },  // Envenomed Spears — CAbilityVenomSpear orc
// TODO: { "Awrp", &a_warp },  // Waygate ability — CAbilityWarp other
// TODO: { "Aweb", &a_auto_target_spell },  // Web — CAbilityAutoTargetSpell undead
// TODO: { "AIa1", &a_attack_mod },  // Item Hero Stat Bonus — CAbilityAttackMod [ITEM] other
// TODO: { "AIa3", &a_attack_mod },  // Item Hero Stat Bonus — CAbilityAttackMod [ITEM] other
// TODO: { "AIa4", &a_attack_mod },  // Item Hero Stat Bonus — CAbilityAttackMod [ITEM] other
// TODO: { "AIa6", &a_attack_mod },  // Item Hero Stat Bonus — CAbilityAttackMod [ITEM] other
// TODO: { "AIx5", &a_attack_speed_bonus },  // Item Hero Stat Bonus — CAbilityAttackSpeedBonus [ITEM] other
// TODO: { "AIx1", &a_attack_speed_bonus },  // Item Hero Stat Bonus — CAbilityAttackSpeedBonus [ITEM] other
// TODO: { "AIx2", &a_attack_speed_bonus },  // Item Hero Stat Bonus — CAbilityAttackSpeedBonus [ITEM] other
// TODO: { "AIs1", &a_damage_bonus_base },  // Item Hero Stat Bonus — CAbilityDamageBonusBase [ITEM] other
// TODO: { "AIs3", &a_damage_bonus_base },  // Item Hero Stat Bonus — CAbilityDamageBonusBase [ITEM] other
// TODO: { "AIs4", &a_damage_bonus_base },  // Item Hero Stat Bonus — CAbilityDamageBonusBase [ITEM] other
// TODO: { "AIs6", &a_damage_bonus_base },  // Item Hero Stat Bonus — CAbilityDamageBonusBase [ITEM] other
// TODO: { "AIi1", &a_intelligence_mod },  // Item Hero Stat Bonus — CAbilityIntelligenceMod [ITEM] other
// TODO: { "AIi3", &a_intelligence_mod },  // Item Hero Stat Bonus — CAbilityIntelligenceMod [ITEM] other
// TODO: { "AIi4", &a_intelligence_mod },  // Item Hero Stat Bonus — CAbilityIntelligenceMod [ITEM] other
// TODO: { "AIi6", &a_intelligence_mod },  // Item Hero Stat Bonus — CAbilityIntelligenceMod [ITEM] other
// TODO: { "AIxm", &a_tome },  // Item Int/Agi/Str gain — CAbilityTome [ITEM] other
// TODO: { "AIam", &a_tome },  // Item Agility Gain — CAbilityTome [ITEM] other
// TODO: { "AIim", &a_tome },  // Item Intelligence Gain — CAbilityTome [ITEM] other
// TODO: { "AIsm", &a_tome },  // Item Strength Gain — CAbilityTome [ITEM] other
// TODO: { "AIaa", &a_damage_bonus_base },  // Item Permanent Damage Gain — CAbilityDamageBonusBase [ITEM] other
// TODO: { "AIat", &a_attack_bonus },  // Item Damage Bonus — CAbilityAttackBonus [ITEM] other
// TODO: { "AIva", &a_attack_mod },  // Item Life Steal — CAbilityAttackMod [ITEM] other
// TODO: { "AIbl", &a_on_fire },  // Build Tiny Castle — CAbilityOnFire [ITEM] other
// TODO: { "AId1", &a_defense_bonus },  // Item Armor Bonus — CAbilityDefenseBonus [ITEM] other
// TODO: { "AId2", &a_defense_bonus },  // Item Armor Bonus — CAbilityDefenseBonus [ITEM] other
// TODO: { "AId3", &a_defense_bonus },  // Item Armor Bonus — CAbilityDefenseBonus [ITEM] other
// TODO: { "AId4", &a_defense_bonus },  // Item Armor Bonus — CAbilityDefenseBonus [ITEM] other
// TODO: { "AId5", &a_defense_bonus },  // Item Armor Bonus — CAbilityDefenseBonus [ITEM] other
// TODO: { "AIgf", &a_attack_speed_bonus },  // Glyph of Fortification — CAbilityAttackSpeedBonus [ITEM] other
// TODO: { "AIgu", &a_strength_mod },  // Glyph of Fortification — CAbilityStrengthMod [ITEM] other
// TODO: { "AIem", &a_experience_mod },  // Item Experience Gain — CAbilityExperienceMod [ITEM] other
// TODO: { "AIfd", &a_agility_mod },  // Item Red Drake Summon — CAbilityAgilityMod [ITEM] other
// TODO: { "AIff", &a_defense_bonus },  // Item Furbolg Summon — CAbilityDefenseBonus [ITEM] other
// TODO: { "AIfr", &a_max_life_bonus },  // Item Rock Golem Summon — CAbilityMaxLifeBonus [ITEM] other
// TODO: { "AIfu", &a_max_mana_bonus },  // Item Doom Guard Summon — CAbilityMaxManaBonus [ITEM] other
// TODO: { "AIfh", &a_attack_speed_bonus },  // Item Felhound Summon — CAbilityAttackSpeedBonus [ITEM] other
// TODO: { "AIfs", &a_figurine },  // Item Skeleton Summon — CAbilityFigurine [ITEM] other
// TODO: { "AIfl", &a_button },  // Item Capture The Flag — CAbilityButton [ITEM] other
// TODO: { "AIfm", &a_button },  // Item Capture The Flag — CAbilityButton [ITEM] other
// TODO: { "AIfo", &a_button },  // Item Capture The Flag — CAbilityButton [ITEM] other
// TODO: { "AIfn", &a_button },  // Item Capture The Flag — CAbilityButton [ITEM] other
// TODO: { "AIfe", &a_button },  // Item Capture The Flag — CAbilityButton [ITEM] other
// TODO: { "AIfa", &a_agility_mod },  // Flare Gun — CAbilityAgilityMod [ITEM] other
// TODO: { "AIlm", &a_level_mod },  // Item Level Gain — CAbilityLevelMod [ITEM] other
// TODO: { "AIlp", &a_lightning_purge },  // Item Purge — CAbilityLightningPurge [ITEM] other
// TODO: { "AIlf", &a_aura_regen_mana },  // Item Life Bonus — CAbilityAuraRegenMana [ITEM] other
// TODO: { "AIl1", &a_regen_base },  // Item Life Bonus — CAbilityRegenBase [ITEM] other
// TODO: { "AIl2", &a_regen_base },  // Item Life Bonus — CAbilityRegenBase [ITEM] other
// TODO: { "AIms", &a_move_speed_bonus },  // Item Move Speed Bonus — CAbilityMoveSpeedBonus [ITEM] other
// TODO: { "ANbs", &a_spell },  // Orb of Darkness — CAbilitySpell [ITEM] other
// TODO: { "AIdf", &a_poison_attack },  // Item Attack Black Arrow Bonus — CAbilityPoisonAttack [ITEM] other
// TODO: { "AIcb", &a_button },  // Item Attack Corruption Bonus — CAbilityButton [ITEM] other
// TODO: { "AIdn", &a_max_mana_bonus },  // Shadow Orb Ability — CAbilityMaxManaBonus [ITEM] other
// TODO: { "AIfb", &a_on_fire },  // Item Attack Fire Bonus — CAbilityOnFire [ITEM] other
// TODO: { "AIzb", &a_frost_nova },  // Item Freeze Damage Bonus — CAbilityFrostNova [ITEM] other
// TODO: { "AIob", &a_frost_nova },  // Item Attack Frost Bonus — CAbilityFrostNova [ITEM] other
// TODO: { "AIll", &a_item_mana_restore },  // Orb of Lightning (new) — CAbilityItemManaRestore [ITEM] other
// TODO: { "AIlb", &a_bounce },  // Item Attack Lightning Bonus — CAbilityBounce [ITEM] other
// TODO: { "AIsb", &a_item_heal },  // Orb of Slow  — CAbilityItemHeal [ITEM] other
// TODO: { "AIpb", &a_item_mana_restore },  // Item Attack Poison Bonus — CAbilityItemManaRestore [ITEM] other
// TODO: { "Apo2", &a_item_invul },  // Poison Sting — CAbilityItemInvul [ITEM] other
// TODO: { "Arel", &a_aura_regen_life },  // Item Life Regeneration — CAbilityAuraRegenLife [ITEM] other
// TODO: { "AIsi", &a_sight_bonus },  // Item Sight Range Bonus — CAbilitySightBonus [ITEM] other
// TODO: { "AIso", &a_simple_spell },  // Item Soul Theft — CAbilitySimpleSpell [ITEM] other
// TODO: { "Asou", &a_simple_spell },  // Item Soul Possession — CAbilitySimpleSpell [ITEM] other
// TODO: { "AIcf", &a_immolation },  // Item Immolation — CAbilityImmolation [ITEM] other
// TODO: { "AIco", &a_button },  // Item Command — CAbilityButton [ITEM] other
// TODO: { "AIdm", &a_bounce },  // Item Area tree/wall damage — CAbilityBounce [ITEM] other
// TODO: { "AIda", &a_item_defense_aoe },  // Item Temporary Area Armor Bonus — CAbilityItemDefenseAoe [ITEM] other
// TODO: { "AIta", &a_item_town_portal },  // Item Area Detection — CAbilityItemTownPortal [ITEM] other
// TODO: { "AIdi", &a_item_dispel_aoe },  // Item Dispel — CAbilityItemDispelAoe [ITEM] other
// TODO: { "AIh1", &a_item_heal },  // Item Healing — CAbilityItemHeal [ITEM] other
// TODO: { "AIh2", &a_item_heal },  // Item Healing — CAbilityItemHeal [ITEM] other
// TODO: { "AIh3", &a_item_heal },  // Least Healing — CAbilityItemHeal [ITEM] other
// TODO: { "AIha", &a_item_heal_aoe },  // Item Area Healing — CAbilityItemHealAoe [ITEM] other
// TODO: { "AIil", &a_item_illusion },  // Item Illusions — CAbilityItemIllusion [ITEM] other
// TODO: { "AIv1", &a_item_invis },  // Item Temporary Invisibility — CAbilityItemInvis [ITEM] other
// TODO: { "AIv2", &a_item_invis },  // Item Temporary Invisibility — CAbilityItemInvis [ITEM] other
// TODO: { "AIvu", &a_item_invul },  // Item Temporary Invulnerability — CAbilityItemInvul [ITEM] other
// TODO: { "AIm1", &a_item_mana_restore },  // Item Mana Regain — CAbilityItemManaRestore [ITEM] other
// TODO: { "AIm2", &a_item_mana_restore },  // Item Mana Regain — CAbilityItemManaRestore [ITEM] other
// TODO: { "AImr", &a_item_mana_restore_aoe },  // Item Area Mana Regain — CAbilityItemManaRestoreAoe [ITEM] other
// TODO: { "AIpm", &a_button },  // Item Place Goblin Land Mine — CAbilityButton [ITEM] other
// TODO: { "AIrt", &a_item_recall },  // Item Recall — CAbilityItemRecall [ITEM] other
// TODO: { "AIrm", &a_item_regen_mana },  // Item Mana Regeneration — CAbilityItemRegenMana [ITEM] other
// TODO: { "AIrc", &a_item_reincarnation },  // Item Reincarnation — CAbilityItemReincarnation [ITEM] other
// TODO: { "AIre", &a_item_restore },  // Item Heal/Mana Regain — CAbilityItemRestore [ITEM] other
// TODO: { "AIra", &a_item_restore_aoe },  // Item Area Heal/Mana Regain — CAbilityItemRestoreAoe [ITEM] other
// TODO: { "AIsp", &a_item_speed },  // Item Temporary Speed Bonus — CAbilityItemSpeed [ITEM] other
// TODO: { "AIsa", &a_item_speed },  // Scroll of Haste — CAbilityItemSpeed [ITEM] other
// TODO: { "AItp", &a_item_town_portal },  // Item Town Portal — CAbilityItemTownPortal [ITEM] other
// TODO: { "AIcd", &a_item_town_portal },  // ItemAuraCommand — CAbilityItemTownPortal [ITEM] other
// TODO: { "AIxs", &a_magic_immunity },  // Item Anti-Magic Shell — CAbilityMagicImmunity [ITEM] other
// TODO: { "AIan", &a_simple_spell },  // Item Animate Dead — CAbilitySimpleSpell [ITEM] other
// TODO: { "AIrs", &a_item_reincarnation },  // Item Resurrection — CAbilityItemReincarnation [ITEM] other
// TODO: { "AImh", &a_item_heal },  // Item Permanent Life Gain — CAbilityItemHeal [ITEM] other
// TODO: { "AImb", &a_item_heal },  // Item Mana Bonus — CAbilityItemHeal [ITEM] other
// TODO: { "AIbm", &a_item_mana_restore },  // Item Mana Bonus — CAbilityItemManaRestore [ITEM] other
// TODO: { "AIsx", &a_attack_speed_bonus },  // Item Attack Speed Bonus — CAbilityAttackSpeedBonus [ITEM] other
// TODO: { "AIs2", &a_item_speed },  // Item Attack Speed Bonus — CAbilityItemSpeed [ITEM] other
// TODO: { "AIrl", &a_item_defense_aoe },  // Healing Salve — CAbilityItemDefenseAoe [ITEM] other
// TODO: { "AIpr", &a_item_invul },  // Clarity Potion — CAbilityItemInvul [ITEM] other
// TODO: { "AIsl", &a_item_speed },  // Scroll of Regeneration — CAbilityItemSpeed [ITEM] other
// TODO: { "AIpl", &a_item_mana_restore },  // Lesser Clarity Potion — CAbilityItemManaRestore [ITEM] other
// TODO: { "AIp1", &a_item_town_portal },  // Generic Item-Rejuv Effect — CAbilityItemTownPortal [ITEM] other
// TODO: { "AIp2", &a_item_town_portal },  // Generic Item-Rejuv Effect — CAbilityItemTownPortal [ITEM] other
// TODO: { "AIp3", &a_item_town_portal },  // Generic Item-Rejuv Effect — CAbilityItemTownPortal [ITEM] other
// TODO: { "AIp4", &a_item_town_portal },  // Generic Item-Rejuv Effect — CAbilityItemTownPortal [ITEM] other
// TODO: { "AIp5", &a_item_town_portal },  // Generic Item-Rejuv Effect — CAbilityItemTownPortal [ITEM] other
// TODO: { "AIp6", &a_item_town_portal },  // Generic Item-Rejuv Effect — CAbilityItemTownPortal [ITEM] other
// TODO: { "AIgo", &a_attack_mod },  // Chest of Gold — CAbilityAttackMod [ITEM] other
// TODO: { "AIlu", &a_item_heal_aoe },  // Bundle of Lumber — CAbilityItemHealAoe [ITEM] other
// TODO: { "AIrv", &a_item_heal_aoe },  // Item Reveal Entire Map — CAbilityItemHealAoe [ITEM] other
// TODO: { "AIdc", &a_item_defense_aoe },  // Item Chain Dispel — CAbilityItemDefenseAoe [ITEM] other
// TODO: { "AIwb", &a_button },  // Item Web — CAbilityButton [ITEM] other
// TODO: { "AImo", &a_item_mana_restore_aoe },  // Monster Lure — CAbilityItemManaRestoreAoe [ITEM] other
// TODO: { "AIct", &a_button },  // Change Time of Day — CAbilityButton [ITEM] other
// TODO: { "AIri", &a_item_speed },  // Random Item — CAbilityItemSpeed [ITEM] other
// TODO: { "AIsr", &a_item_speed },  // Spell Damage Reduction — CAbilityItemSpeed [ITEM] other
// TODO: { "Ablp", &a_item_heal },  // Blight Placement — CAbilityItemHeal [ITEM] other
// TODO: { "AIpv", &a_item_mana_restore_aoe },  // Vampiric Potion — CAbilityItemManaRestoreAoe [ITEM] other
// TODO: { "Aste", &a_figurine_rock_golem },  // Steal — CAbilityFigurineRockGolem [ITEM] other
// TODO: { "Amec", &a_button },  // Mechanical Critter — CAbilityButton [ITEM] other
// TODO: { "Ashs", &a_spell },  // Wand of Shadowsight — CAbilitySpell [ITEM] other
// TODO: { "ANpr", &a_button },  // Staff of Preservation — CAbilityButton [ITEM] other
// TODO: { "ANsa", &a_bounce },  // Staff of Sanctuary — CAbilityBounce [ITEM] other
// TODO: { "ANss", &a_bounce },  // Spell Shield — CAbilityBounce [ITEM] other
// TODO: { "ANse", &a_spell },  // Spell Shield — CAbilitySpell [ITEM] other
// TODO: { "Aret", &a_revive },  // Tome of Retraining — CAbilityRevive [ITEM] other
// TODO: { "Aspb", &a_bounce },  // Spell Book — CAbilityBounce [ITEM] other
// TODO: { "AIrd", &a_item_dispel_aoe },  // Raise Dead (Item) — CAbilityItemDispelAoe [ITEM] other
// TODO: { "AItb", &a_button },  // Dust of Appearance — CAbilityButton [ITEM] other
// TODO: { "AIrb", &a_item_heal_aoe },  // Rebirth — CAbilityItemHealAoe [ITEM] other
// TODO: { "AUds", &a_mass_teleport },  // Dark Summoning — CAbilityMassTeleport [ITEM] other
// TODO: { "AId0", &a_item_dispel_aoe },  // Item Armor Bonus — CAbilityItemDispelAoe [ITEM] other
// TODO: { "AImz", &a_item_mana_restore_aoe },  // Item Mana Bonus (100) — CAbilityItemManaRestoreAoe [ITEM] other
// TODO: { "AImv", &a_item_mana_restore_aoe },  // Item Mana Bonus (75) — CAbilityItemManaRestoreAoe [ITEM] other
// TODO: { "AIpx", &a_max_life_bonus },  // Item Permanent Life Gain — CAbilityMaxLifeBonus [ITEM] other
// TODO: { "AIdd", &a_item_heal },  // Defend — CAbilityItemHeal [ITEM] other
// TODO: { "AId8", &a_item_town_portal },  // Item Armor Bonus — CAbilityItemTownPortal [ITEM] other
// TODO: { "AId7", &a_item_dispel_aoe },  // Item Armor Bonus — CAbilityItemDispelAoe [ITEM] other
// TODO: { "AIlz", &a_regen_base },  // Item Life Bonus — CAbilityRegenBase [ITEM] other
// TODO: { "AIhx", &a_item_heal },  // Item Healing — CAbilityItemHeal [ITEM] other
// TODO: { "AIaz", &a_item_defense_aoe },  // Item Hero Stat Bonus — CAbilityItemDefenseAoe [ITEM] other
// TODO: { "AIsh", &a_item_town_portal },  // Summon Headhunter — CAbilityItemTownPortal [ITEM] other
// TODO: { "AI2m", &a_defense_bonus },  // Item Mana Bonus (200) — CAbilityDefenseBonus [ITEM] other
// TODO: { "AIx3", &a_attack_speed_bonus },  // (All + 3) — CAbilityAttackSpeedBonus [ITEM] other
// TODO: { "AIx4", &a_attack_speed_bonus },  // (All + 4) — CAbilityAttackSpeedBonus [ITEM] other
};

ability_t const *FindAbilityByClassname(LPCSTR classname) {
    FOR_LOOP(i, game.num_abilities) {
        if (!abilitylist[i].classname)
            continue;
        if (!strcmp(abilitylist[i].classname, classname))
            return abilitylist[i].ability;
    }
    return NULL;
}

/* Command-card names use two namespaces. Engine commands (CmdBuild, CmdMove,
 * etc.) are full strings registered directly in abilitylist. WC3 abilities are
 * four-character rawcodes whose AbilityData alias may point at a base handler.
 * Only rawcodes belong in the SLK resolver: passing CmdBuild through FS_SLKKey
 * truncates it to CmdB and loses the registered build command. */
ability_t const *FindAbilityForCommand(LPCSTR classname) {
    if (!classname || !*classname) {
        return NULL;
    }
    if (strlen(classname) != 4) {
        return FindAbilityByClassname(classname);
    }
    return FindAbilityByClassname(GetClassName(G_AbilityCodeName(classname)));
}

static BOOL unit_has_ability_handler(LPEDICT ent, ability_t const *wanted) {
    LPCSTR abilities;

    if (!ent || !wanted || !ent->data.UnitAbilities) return false;
    abilities = ent->data.UnitAbilities->abilList;
    if (!abilities) return false;

    PARSE_LIST(abilities, ability_name, parse_segment) {
        if (FindAbilityForCommand(ability_name) == wanted) return true;
    }
    return false;
}

BOOL G_UnitAutocastIsOn(LPEDICT ent, ability_t const *ability) {
    return ent && ability && ability->autocast_is_on && unit_has_ability_handler(ent, ability) &&
           ability->autocast_is_on(ent);
}

BOOL G_SetUnitAutocast(LPEDICT ent, ability_t const *ability, BOOL enabled) {
    LPCSTR abilities;

    if (!ent || !ability || !ability->autocast_set || !unit_has_ability_handler(ent, ability)) {
#ifdef WC3_DEBUG_AUTOCAST
        if (G_AutocastDebugLevel() >= 1) {
            fprintf(stderr, "WC3_AUTOCAST toggle rejected unit=%ld ability=%p enabled=%d flags=0x%x\n",
                    ent && g_edicts ? (long)(ent - g_edicts) : -1L, (void *)ability,
                    enabled ? 1 : 0, ent ? ent->aiflags : 0);
        }
#endif
        return false;
    }

    /* Warsmash keeps one selected autocast ability per unit. Turning a new one
     * on first disables every other autocast-capable ability currently present
     * on this unit; abilities without autocast hooks remain untouched. */
    if (enabled && ent->data.UnitAbilities && (abilities = ent->data.UnitAbilities->abilList)) {
        PARSE_LIST(abilities, ability_name, parse_segment) {
            ability_t const *other = FindAbilityForCommand(ability_name);
            if (other && other != ability && other->autocast_set) other->autocast_set(ent, false);
        }
    }
    ability->autocast_set(ent, enabled);
    if (enabled) {
        ent->aiflags |= AI_AUTOCAST_ACTIVE;
    } else {
        BOOL any_enabled = false;
        if (ent->data.UnitAbilities && (abilities = ent->data.UnitAbilities->abilList)) {
            PARSE_LIST(abilities, ability_name, parse_segment) {
                ability_t const *other = FindAbilityForCommand(ability_name);
                if (other && other->autocast_is_on && other->autocast_is_on(ent)) {
                    any_enabled = true;
                    break;
                }
            }
        }
        if (!any_enabled) ent->aiflags &= ~AI_AUTOCAST_ACTIVE;
    }
#ifdef WC3_DEBUG_AUTOCAST
    if (G_AutocastDebugLevel() >= 1) {
        fprintf(stderr, "WC3_AUTOCAST toggle unit=%ld class=%.4s enabled=%d flags=0x%x idle_worker=%d abilities=%s\n",
                g_edicts ? (long)(ent - g_edicts) : -1L, (LPCSTR)&ent->class_id,
                enabled ? 1 : 0, ent->aiflags, G_UnitIsIdleWorker(ent) ? 1 : 0,
                ent->data.UnitAbilities && ent->data.UnitAbilities->abilList ? ent->data.UnitAbilities->abilList : "<none>");
    }
#endif
    return true;
}

BOOL G_TryUnitAutocast(LPEDICT ent) {
    LPCSTR abilities;

    if (!ent || !(ent->aiflags & AI_AUTOCAST_ACTIVE) || !ent->data.UnitAbilities ||
        !(abilities = ent->data.UnitAbilities->abilList)) {
#ifdef WC3_DEBUG_AUTOCAST
        if (G_AutocastDebugLevel() >= 2 && ent) {
            fprintf(stderr, "WC3_AUTOCAST skip unit=%ld class=%.4s flags=0x%x abilities=%s\n",
                    g_edicts ? (long)(ent - g_edicts) : -1L, (LPCSTR)&ent->class_id,
                    ent->aiflags,
                    ent->data.UnitAbilities && ent->data.UnitAbilities->abilList ? ent->data.UnitAbilities->abilList : "<none>");
        }
#endif
        return false;
    }
#ifdef WC3_DEBUG_AUTOCAST
    if (G_AutocastDebugLevel() >= 2) {
        fprintf(stderr, "WC3_AUTOCAST try unit=%ld class=%.4s flags=0x%x abilities=%s\n",
                g_edicts ? (long)(ent - g_edicts) : -1L, (LPCSTR)&ent->class_id,
                ent->aiflags, abilities);
    }
#endif
    PARSE_LIST(abilities, ability_name, parse_segment) {
        ability_t const *ability = FindAbilityForCommand(ability_name);
        BOOL is_on;
        if (!ability || !ability->autocast_is_on || !ability->autocast_acquire) continue;
        is_on = ability->autocast_is_on(ent);
#ifdef WC3_DEBUG_AUTOCAST
        if (G_AutocastDebugLevel() >= 2) {
            fprintf(stderr, "WC3_AUTOCAST ability unit=%ld code=%s on=%d\n",
                    g_edicts ? (long)(ent - g_edicts) : -1L, ability_name, is_on ? 1 : 0);
        }
#endif
        if (is_on && ability->autocast_acquire(ent)) {
#ifdef WC3_DEBUG_AUTOCAST
            if (G_AutocastDebugLevel() >= 1) {
                fprintf(stderr, "WC3_AUTOCAST acquired unit=%ld code=%s\n",
                        g_edicts ? (long)(ent - g_edicts) : -1L, ability_name);
            }
#endif
            return true;
        }
    }
#ifdef WC3_DEBUG_AUTOCAST
    if (G_AutocastDebugLevel() >= 2) {
        fprintf(stderr, "WC3_AUTOCAST no_target unit=%ld\n",
                g_edicts ? (long)(ent - g_edicts) : -1L);
    }
#endif
    return false;
}

DWORD FindAbilityIndex(LPCSTR classname) {
    FOR_LOOP(i, game.num_abilities) {
        if (!abilitylist[i].classname)
            continue;
        if (!strcmp(abilitylist[i].classname, classname))
            return i;
    }
    return 255;
}

void InitAbilities(void) {
    game.num_abilities = sizeof(abilitylist)/sizeof(abilitylist[0]);
    FOR_LOOP(i, game.num_abilities) {
        abilityitem_t *abil = &abilitylist[i];
        if (abil->ability->init) {
            abil->ability->init(abil->classname, abil->ability);
        }
    }
}

void SetAbilityNames(void) {
//    FOR_LOOP(i, game.num_abilities) {
//        if (!abilitylist[i].classname)
//            continue;
//        abilityitem_t *abil = &abilitylist[i];
//    }
}

ability_t const *GetAbilityByIndex(DWORD index) {
    if (index >= game.num_abilities)
        return NULL;
    return abilitylist[index].ability;
}

DWORD GetAbilityIndex(ability_t const *ability) {
    FOR_LOOP(i, game.num_abilities) {
        if (abilitylist[i].ability == ability) {
            return i;
        }
    }
    return 255;
}
