#include <ctype.h>
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STB_IMAGE_IMPLEMENTATION
#include "../renderer/stb/stb_image.h"

static void usage(void) {
    fprintf(stderr,
            "Usage: png2sysfont <input.png> <output.h> <symbol> [cell_width cell_height]\n"
            "\n"
            "Converts an RGBA PNG atlas into a C header containing RLE RGBA bytes.\n"
            "The atlas is expected to contain a 16-column character grid.\n");
}

static int parse_positive_int(char const *text, int *out) {
    char *end = NULL;
    long value;

    errno = 0;
    value = strtol(text, &end, 10);
    if (errno || !end || *end || value <= 0 || value > 65535) {
        return 0;
    }

    *out = (int)value;
    return 1;
}

static void make_macro_name(char *dst, size_t dst_size, char const *symbol, char const *suffix) {
    size_t i;
    size_t out = 0;

    for (i = 0; symbol[i] && out + 1 < dst_size; i++) {
        unsigned char ch = (unsigned char)symbol[i];
        dst[out++] = (char)(isalnum(ch) ? toupper(ch) : '_');
    }

    if (suffix) {
        for (i = 0; suffix[i] && out + 1 < dst_size; i++) {
            unsigned char ch = (unsigned char)suffix[i];
            dst[out++] = (char)(isalnum(ch) ? toupper(ch) : '_');
        }
    }

    dst[out] = 0;
}

static int same_pixel(unsigned char const *a, unsigned char const *b) {
    return a[0] == b[0] && a[1] == b[1] && a[2] == b[2] && a[3] == b[3];
}

int main(int argc, char **argv) {
    char const *input;
    char const *output;
    char const *symbol;
    char guard[256];
    char macro[256];
    FILE *fp;
    unsigned char *pixels;
    int width;
    int height;
    int channels;
    int cell_width = 16;
    int cell_height = 16;
    int cols;
    int rows;
    int count;
    int rle_size;
    int i;
    int line_runs;

    if (argc != 4 && argc != 6) {
        usage();
        return 1;
    }

    input = argv[1];
    output = argv[2];
    symbol = argv[3];

    if (argc == 6) {
        if (!parse_positive_int(argv[4], &cell_width) ||
            !parse_positive_int(argv[5], &cell_height)) {
            fprintf(stderr, "Invalid cell size\n");
            return 1;
        }
    }

    pixels = stbi_load(input, &width, &height, &channels, 4);
    if (!pixels) {
        fprintf(stderr, "%s: %s\n", input, stbi_failure_reason());
        return 1;
    }

    if (width <= 0 || height <= 0 || width % cell_width || height % cell_height) {
        fprintf(stderr, "%s: image size %dx%d is not divisible by cell size %dx%d\n",
                input, width, height, cell_width, cell_height);
        stbi_image_free(pixels);
        return 1;
    }

    cols = width / cell_width;
    rows = height / cell_height;
    if (cols != 16) {
        fprintf(stderr, "%s: expected 16 columns, got %d\n", input, cols);
        stbi_image_free(pixels);
        return 1;
    }

    fp = fopen(output, "w");
    if (!fp) {
        fprintf(stderr, "%s: %s\n", output, strerror(errno));
        stbi_image_free(pixels);
        return 1;
    }

    make_macro_name(guard, sizeof(guard), symbol, "_h");

    fprintf(fp, "#ifndef %s\n", guard);
    fprintf(fp, "#define %s\n\n", guard);
    fprintf(fp, "/* Generated by tools/png2sysfont.c from %s. */\n", input);

    make_macro_name(macro, sizeof(macro), symbol, "_width");
    fprintf(fp, "#define %s %d\n", macro, width);
    make_macro_name(macro, sizeof(macro), symbol, "_height");
    fprintf(fp, "#define %s %d\n", macro, height);
    make_macro_name(macro, sizeof(macro), symbol, "_cols");
    fprintf(fp, "#define %s %d\n", macro, cols);
    make_macro_name(macro, sizeof(macro), symbol, "_rows");
    fprintf(fp, "#define %s %d\n", macro, rows);
    make_macro_name(macro, sizeof(macro), symbol, "_cell_width");
    fprintf(fp, "#define %s %d\n", macro, cell_width);
    make_macro_name(macro, sizeof(macro), symbol, "_cell_height");
    fprintf(fp, "#define %s %d\n\n", macro, cell_height);

    count = width * height;
    rle_size = 0;
    for (i = 0; i < count;) {
        int run = 1;
        while (i + run < count &&
               run < 65535 &&
               same_pixel(pixels + i * 4, pixels + (i + run) * 4)) {
            run++;
        }
        rle_size += 6;
        i += run;
    }

    make_macro_name(macro, sizeof(macro), symbol, "_rle_size");
    fprintf(fp, "#define %s %d\n\n", macro, rle_size);

    fprintf(fp, "static const unsigned char %s_rle[%d] = {\n", symbol, rle_size);
    line_runs = 0;
    for (i = 0; i < count;) {
        unsigned char const *p = pixels + i * 4;
        int run = 1;
        unsigned char bytes[6];
        int b;

        while (i + run < count &&
               run < 65535 &&
               same_pixel(p, pixels + (i + run) * 4)) {
            run++;
        }

        bytes[0] = (unsigned char)(run & 0xff);
        bytes[1] = (unsigned char)((run >> 8) & 0xff);
        bytes[2] = p[0];
        bytes[3] = p[1];
        bytes[4] = p[2];
        bytes[5] = p[3];

        if (line_runs == 0) {
            fprintf(fp, "    ");
        }

        for (b = 0; b < 6; b++) {
            fprintf(fp, "0x%02x", bytes[b]);
            if (i + run < count || b + 1 < 6) {
                fprintf(fp, ",");
            }
            if (b + 1 < 6) {
                fprintf(fp, " ");
            }
        }
        i += run;
        line_runs++;
        if (line_runs == 4 || i >= count) {
            fprintf(fp, "\n");
            line_runs = 0;
        } else {
            fprintf(fp, " ");
        }
    }
    fprintf(fp, "};\n\n");
    fprintf(fp, "#endif\n");

    if (fclose(fp) != 0) {
        fprintf(stderr, "%s: %s\n", output, strerror(errno));
        stbi_image_free(pixels);
        return 1;
    }

    stbi_image_free(pixels);
    return 0;
}
